{"uuid": "fd290183-c263-4083-b6f3-47789feaa054", "children": ["f7ac915a-6c9d-4031-9392-96acf456eb7e"], "befores": [{"name": "web_driver", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "trace": "  File \"c:\\python\\tools\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\python\\pythonWorkSpace\\PythonAutoTest\\PythonAutoTest\\conftest.py\", line 25, in web_driver\n    service = Service(EdgeChromiumDriverManager().install())\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\microsoft.py\", line 73, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 107, in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\drivers\\edge.py\", line 51, in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n  File \"c:\\python\\tools\\python\\lib\\site-packages\\webdriver_manager\\core\\http.py\", line 35, in get\n    raise exceptions.ConnectionError(f\"Could not reach host. Are you offline?\")\n"}, "start": 1752624004803, "stop": 1752624008010}], "start": 1752624004803, "stop": 1752624008999}